### ISSUE TITLE
Offset issue

### ISSUE THREAD

**Issue by oldnapalm** [gtbikev/route-builder#28]
If I enable offset the decimal separator gets lost. I guess it's because in my region it's defined as comma instead of dot.

E.g. set Z offset as 1,000 (even if I change comma to dot, it goes back to comma when focus leaves the widget)

```
      <Position>
        <X>-2956.02075</X>
        <Y>3511.953</Y>
        <Z>7.571887</Z>
      </Position>
```

becomes

```
    {
      "X": -295602075,
      "Y": 3511953,
      "Z": 7571888
    },
```

**Comment by murech** [comment]
I decided to work on other projects which means that there will be no more updates for route builder. This repository will be archived.
